name: cinder-volume
base: core24
version: "2025.1"
summary: cinder-volume in a snap
description: |
  This snap is a base snap for cinder-volume. It intended to be used
  directly for supported plugins, but can be used a base for other snaps
  that need to include cinder-volume.

grade: stable
confinement: strict

package-repositories:
  - type: apt
    cloud: epoxy
    priority: always
    pocket: proposed

environment:
  LC_ALL: C
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/usr/local/bin:$SNAP/usr/local/sbin:$PATH
  PYTHONPATH: $SNAP/usr/lib/python3.12:$SNAP/usr/lib/python3.12/site-packages:$SNAP/lib/python3.12:$SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH

layout:
  /etc/iscsi:
    bind: $SNAP_COMMON/etc/iscsi
  /usr/bin/findmnt:
    bind-file: $SNAP/usr/bin/findmnt

apps:
  cinder-volume:
    environment:
      # Standard library components must have priority in module name resolution: https://storyboard.openstack.org/#!/story/2007806
      PYTHONPATH: $PYTHONPATH:$SNAP/usr/lib/python3.12:$SNAP/usr/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.12:$SNAP/lib/python3.12/site-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/ceph
    command: bin/cinder_volume
    daemon: simple
    plugs:
      - network
      - network-bind
      - mount-observe
      - block-devices
      - system-observe
      - hardware-observe
      - log-observe
      - network-observe
      - etc-iscsi
      - nvme-identity

plugs:
  etc-iscsi:
    interface: system-files
    read:
      - /etc/iscsi/initiatorname.iscsi
  nvme-identity:
    interface: system-files
    read:
      - /etc/nvme/hostnqn
      - /etc/nvme/hostid

parts:
  openstack:
    plugin: nil
    stage-packages:
      - python3-cinder
      - cinder-volume
      - sysfsutils
      - python3-rtslib-fb
      - python3-minimal
      - python3-tz
      - ceph-common
      - nfs-common
      - tgt
      - util-linux
    override-build: |
      craftctl default
      # purge some dangling symlinks
      rm -rf $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/iab.txt
      rm -rf $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/oui.txt
      # rewrite symlink
      rm -rf $CRAFT_PART_INSTALL/usr/bin/iscsiadm
    override-prime: |
      craftctl default
      target=$CRAFT_PRIME/usr/bin/iscsiadm
      if [ -L "$target" ]; then
        rm -f "$target"
      fi
      ln -s ../sbin/iscsiadm "$target"

  cinder-volume:
    after: [openstack]
    plugin: python
    source: .
    build-packages:
      - git
    python-requirements:
      - requirements.txt
    override-build: |
      craftctl default
      cinder-snap-helpers write-hooks

  bin:
    source: bin/
    plugin: dump
    organize:
      "*": usr/bin/

hooks:
  install:
    plugs: [network]
  configure:
    plugs:
      - network
      - network-control
      - firewall-control
