name: Tests
on:
  workflow_call:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e pep8
  mypy:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          python3 -m pip install tox
          sudo snap install astral-uv --channel latest/stable --classic
      - name: Run linters
        run: tox -e mypy
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          python -m pip install tox
          sudo snap install astral-uv --channel latest/stable --classic
      - name: Run tests
        run: tox -e py3
